# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH="$HOME/.bin/:$HOME/.local/bin:$PATH"

# Set your environment
# WORK_ENV=true(work setup) or WORK_ENV=false(home setup)
WORK_ENV=true
JOB=groq
SETUP_DIR="$HOME/git/setup"
DOTFILE_FILE=(.aliases .tmux.conf .vimrc .zprofile .vim .p10k.zsh)
DOTFILE_DIR="$SETUP_DIR/dotfiles"
WORK_FILE=(.aliases-$JOB .zshrc-$JOB)
WORK_DIR="$SETUP_DIR/$JOB"

fzf_setup() {
    # fzf
    if command -v fzf >/dev/null; then
        source <(fzf --zsh)
    else
        echo "⚠️ fzf not found! Consider installing via brew install fzf"
    fi

    source "$HOME/.fzf-tab/fzf-tab.plugin.zsh"

    # fzf-tab config
    zstyle ':fzf-tab:*' use-fzf-default-opts yes
    zstyle ':completion:*:descriptions' format '[%d]'
    zstyle ':completion:*' menu select
    zstyle ':completion:*' list-dirs-first true
    zstyle ':fzf-tab:*' fzf-command 'fzf --exact'
    zstyle ':fzf-tab:*' fzf-command fzf
    zstyle ':fzf-tab:*' fzf-bindings 'tab:down,shift-tab:up'
    zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls -alhG --color=always $word'
    zstyle ':fzf-tab:complete:ls:*' fzf-preview 'ls -alhG --color=always $realpath'
    zstyle ':fzf-tab:complete:bat:*' fzf-preview 'bat --style=plain --theme="gruvbox-dark" --color=always $realpath'
    zstyle ':completion:*:*:cd:*' ignored-patterns ''
    zstyle ':completion:*:cd:*' hidden all

    setopt globdots             # include dotfiles in filename globs like *

    export FZF_DEFAULT_OPTS="
    --height=40%
    --layout=reverse
    --border=rounded
    --color=fg:#dcdccc,bg:#1c1c1c,preview-bg:#1c1c1c,border:#5f5faf,header:#af87d7
    --prompt='❯ '
    --marker='✓ '
    --pointer='>'
    --info=inline
    --preview 'bat --style=plain --theme=gruvbox-dark --color=always --line-range :500 {}'
    --bind 'tab:down,shift-tab:up'
    "
}

load_base_env() {
    # Colorful grep
    export GREP_COLORS='1;35;40'

    # less command like vim
    export LESS='-F -R -M -i -N -j5 -X'

    # ls command colors
    export LSCOLORS="ExGxxxxxCxxxxxxxxxxxxx"

    # auto complete
    autoload -Uz compinit && compinit

    # not sure what i did
    autoload -Uz colors && colors
    
    # load fzf function
    fzf_setup

    # allow prompt updates ie date/time
    setopt PROMPT_SUBST

    # make '#' work in interactive shells
    setopt INTERACTIVE_COMMENTS

    # Load dotfiles:
    for file in "${DOTFILE_FILE[@]}"; do
        [[ -r "$DOTFILE_DIR/$file" ]] && [[ -f "$DOTFILE_DIR/$file" ]] && source "$DOTFILE_DIR/$file" 2>/dev/null
    done
    unset file

    source "$HOME/.bin/functions-home.sh"

    source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
    source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

    #if type brew &>/dev/null; then
    #    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
    #fi
    
    HISTFILE=~/.zsh_history
    HISTSIZE=10000
    SAVEHIST=10000
    setopt INC_APPEND_HISTORY SHARE_HISTORY

}

# Load dotfiles based on environment
if $WORK_ENV ; then
    for file in "${WORK_FILE[@]}"; do
        [[ -f "$WORK_DIR/$WORK_FILE" ]] && source "$WORK_DIR/$WORK_FILE"
    done

    export PATH="$HOME/git/setup/$JOB/bin-$JOB:$PATH"
    source "$HOME/git/setup/$JOB/bin-$JOB/functions-$JOB.sh"

    load_base_env

elif ! $WORK_ENV ; then
    load_base_env

else
    echo "⚠️ Unknown value for WORK_ENV: '$WORK_ENV' — must be 'true' or 'false'"
fi

# Generated by Groq bootstrap; START; DO NOT EDIT.
#source $HOME/.config/groq-bootstrap/groq-bootstrap.zsh
# Generated by Groq bootstrap; END; DO NOT EDIT.
